version: "3.8"
services:
  db:
    container_name: "db_my_mini_shop"
    image: postgres:16
    restart: always
    env_file:
      - .env-docker
    ports:
      - "5438:5432"
    networks:
      - custom


networks:
  custom:
    driver: bridge